<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/shared-gallery/Public/css/style.css">
    <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
    <title>Shared gallery</title>
</head>

<body>

<?php 
if(\Core\Auth::getInstance()->isLoggedIn()):?>
<div class="sidebar">
    <div class="sidebar-logo">
        <img src="/shared-gallery/Public/images/user.jpg">
        <p><?= \Core\Auth::getInstance()->getCurrentUser()->getUsername(); ?></p>
        <a href="/shared-gallery/myaccount">My account</a>
    </div>
    <ul class="sidebar-items">
    <li>
        <a href="/shared-gallery">
            <i class='bx bx-home-alt-2'></i>
            <p>Home</p>
        </a>
    </li>
    <li>
        <a href="/shared-gallery/management">
            <i class='bx bxs-dashboard'></i>
            <p>Management</p>
        </a>
    </li>
    <li>
        <a href="/shared-gallery/login/logoutSubmit">
            <i class='bx bx-log-out'></i>
            <p>Logout</p>
        </a>
    </li>
    </ul>
</div>
<?php endif; ?>
<div class="sidebar-toggler">
    <span></span>
    <span></span>
    <span></span>
</div>
<div class="edit">
    <h1>Change Password</h1>
    <?php if (isset($message)): ?>
    <div>
        <p class="alert-danger">
            <?php echo $message; ?>
        </p>
    </div>
    <?php endif ?>

    <form action="<?= URL_ROOT;?><?= "myaccount/updatePasswordSubmit/" . $data['users']->getid();?>" method="post" class="change-password-form">
        <label for="old-password">Old Password</label>
        <input type="password" id="old-password" class="form-control  <?= isset($_SESSION['form_errors']['old-password']) ? 'is-invalid' : ''; ?>"
        name="old-password" placeholder="Old password" required>
        <small class="text-danger"><?= isset($_SESSION['form_errors']['old-password']) ? $_SESSION['form_errors']['old-password'] : ''; ?></small><br>
        <label for="password">New Password</label>
        <input type="password" id="password"
        class="form-control  <?= isset($_SESSION['form_errors']['password']) ? 'is-invalid' : ''; ?>"
        name="password" placeholder="New password" required>
        <small class="text-danger"><?= isset($_SESSION['form_errors']['password']) ? $_SESSION['form_errors']['password'] : ''; ?></small><br>
        <input id="change-pass-btn" type="submit" value="Update">
    </form>
</div>

</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="/shared-gallery/Public/js/script.js"></script>
