<?php include_once INCLUDE_PATH .'header.phtml'; ?>
    <body>
    <?php include_once INCLUDE_PATH .'sidebar.phtml'; ?>
        <div class="myaccount">
            <?php foreach($data['users'] as $user): ?>
        <div class="card ">
            <img src="images/user.jpg" class="card-img-top">
            <div class="card-body">
                <h5 class="card-title"><?= $user->getusername(); ?></h5>
                <p class="card-text"><?= $user->getemail(); ?></p>
            </div>
            
        </div>
            <?php endforeach;?>
        </div>
                <a href="/shared-gallery/myaccount/edit/<?= $user->id; ?>">
                <button class="edit-btn">Edit</button>
            </a>
                <form action="<?= URL_ROOT; ?>myaccount/removeSubmit/<?= $user->id; ?>" method="POST" class="delete-form">
                    <button type="submit" class="remove-acc-btn">Remove account</button>
                </form>
                
    </body>       

<?php include_once INCLUDE_PATH . 'footer.phtml'; ?>