<?php include_once INCLUDE_PATH .'header.phtml'; ?>
    <body>
    <?php include_once INCLUDE_PATH .'sidebar.phtml'; ?>
        <div class="myaccount">
            <?php foreach($data['users'] as $user): ?>
        <div class="card ">
            <img src="images/user.jpg" class="card-img-top">
            <div class="card-body">
                <h5 class="card-title"><?= $user->getusername(); ?></h5>
                <p class="card-text"><?= $user->getemail(); ?></p>
            </div>
            
        </div>
            <?php endforeach;?>
        </div>
                <a class="btnedit" href="/shared-gallery/myaccount/edit/<?= $user->id; ?>">Edit</a>
    </body>       

<?php include_once INCLUDE_PATH . 'footer.phtml'; ?>