<?php include INCLUDE_PATH .'/header.phtml'; ?>
<body>
<?php include INCLUDE_PATH .'/sidebar.phtml'; ?>
<div class="management">
        <table class="table-management">
            <thead class="table-head-management">
                <th>Username</th>
                <th>Email</th>
                <th>Photos</th>
            </thead>
        <?php foreach ($data['gallery'] as $user): ?>
            <tbody>
                <tr>
                    <td> <?=$user->getusername(); ?></td>
                    <td> <?=$user->getemail(); ?></td>
                    <td></td>
                </tr>
            </tbody>
            <?php endforeach;?>
        </table>
        <form action="" method="POST" enctype="multipart/form-data" class="form-upload">
        <input type="file" name="image">
        <button>UPLOAD</button>
        </form>
    </div>
    
    
</body>
<?php include INCLUDE_PATH .'/footer.phtml'; ?>

